### ISSUE TITLE
API rate limit exceeded when running Jekyll locally

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/community-translations-standard#47]
I get a whole lot of

`GitHub Metadata: GET https://api.github.com/repos/<my personal repositories>/contributors?per_page=100`

when running Jekyll locally to compile the page.

Does anyone know what triggers this, and why?

**Comment by ericherman** [comment]
I have seen this in the past with jekyll built sites, and I can reproduce the issue today:

```
~/src/community-translations-standard$ script/test-without-link-check.sh 
Configuration file: /home/eric/src/community-translations-standard/_config.yml  
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem         
            Source: /home/eric/src/community-translations-standard              
       Destination: /home/eric/src/community-translations-standard/_site        
 Incremental build: disabled. Enable with --incremental                         
      Generating...                                                             
      Remote Theme: Using theme standard-for-public-code/jekyll-theme           
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: GET https://api.github.com/repos/publiccodenet/processcode.publiccode.net/contributors?per_page=100: 403 - API rate limit exceeded for [IP ADDRESS REDACTED]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/publiccodenet/product-steering/releases?per_page=100: 403 - API rate limit exceeded for [IP ADDRESS REDACTED]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
```

and that message repeats many, many times.

I suspect this is because the jekyll theme used fetches some metadata repeatedly during the process.

I believe that it will honour the `PAGES_REPO_NWO` environment variable in order to get metadata from that repository.
However, I do not know _why_ the theme requests metadata, nor _what_ metadata is requested .... Nor do I know why it does this more than once during any given build rather than _cache_ it.

Regardless, failing to fetch the metadata does not seem to cause the resulting site to be built any differently ... if there is a difference, it is not obvious to me.

Do you notice any differences with the locally built site after the errors display?

I understand there was some discussion in the main standard-for-public-code repository to change the theme; perhaps as that work is done, this questions about what metadata would be needed (and why) can be investigated.

**Comment by ericherman** [comment]
A glance at github.com/publiccodenet/jekyll-theme shows there are many uses of the github metadata

*  https://github.com/publiccodenet/jekyll-theme/blob/master/site.json
   * site.github
*  https://github.com/publiccodenet/jekyll-theme/blob/master/_includes/footer.liquid
    * site.github
    * site.github.releases
    * site.github.repository_url
    * site.github.repository_nwo
    * site.github.license
    * site.github.license.name
* https://github.com/publiccodenet/jekyll-theme/blob/master/_includes/page-information.liquid
    * site.github.public_repositories
    * site.github.repository_name
    * site.github.repository_url
    * site.github.source.branch

Given the rate-limit exceeded, I wonder if for each page, for each use, each of these are bits of metadata are being re-fetched because they are being pulled in by the footer.

If the plan is to stick to Jekyll, it might be possible to avoid fetching them, perhaps by hard-coding these values in the `_config.yml` or similar.

**Comment by jgroenen** [comment]
I added `repository: codefornl/community-translations-standard` to _config.yml, seems to fix some things
